### PR TITLE
Support Gurobi 10.0

### PR DESCRIPTION
**Pull request by metab0t**
The Clang.jl script uses an old version, so I downloaded Julia 1.5 to generate the 10.0 bindings. Maybe we should update to latest Clang.jl in the future🤔

Tests all pass locally.

### CODE REVIEW

**Review by odow — APPROVED** [review]
Looks good. I'll merge this then update the binaries.

**Comment by odow** [comment]
Was this for a beta release?

**Comment by metab0t** [comment]
It has not been officially announced but the download link for 10.0 is available (by inferring the URL pattern).

**Comment by odow** [comment]
> It has not been officially announced but the download link for 10.0 is available

Haha. I'll wait for the official announcement to update the binaries.

**Pull request merged**
