### PR TITLE
Add continuous integration

### PR DESCRIPTION
**Pull request by odow**
No idea if this will work, but let's see.

cc @simonbowly

### CODE REVIEW

**Comment by odow** [comment]
Success 
image

**Comment by odow** [comment]
Artifacts are pretty cool: https://pkgdocs.julialang.org/v1/artifacts/. They make including downloads like this trivial!

**Comment by simonbowly** [comment]
Nice one!  I made some progress testing the license - evidently I didn't quite configure it right, but copying in the license file from a repo secret mostly does the trick.

image

**Comment by odow** [comment]
@simonbowly I've invited you as an admin user. That should mean you have permission to upload secrets. Let me know if that isn't the case.

**Comment by simonbowly** [comment]
Cheers - I'm just testing using my own license at the moment so will wait for yours to be issued (almost sorted I think).

**Comment by simonbowly** [comment]
Got the license configuration worked out - tests running ok on my master branch.  Now just need to sort out your license (getting there sorry!)  I had to change the artifacts usage slightly to get this running, not really sure why...

image

**Comment by odow** [comment]
> I had to change the artifacts usage

You probably have an existing `deps.jl` file in your local clone of the repository?

You should have permission to push new commits to this branch, or edit the files via the web editor.

**Comment by simonbowly** [comment]
Done - I pushed just the CI change to this PR and now see the Artifacts error at build time. "Artifacts not defined"?

**Comment by odow** [comment]
Oops. I was being too clever when I squashed all my test commits. Working now.

Did you upload the secret? I can't see it

image

**Comment by simonbowly** [comment]
Nice one. I didn't yet - I was using my own license key to test on my fork. Would rather wait for the one issued specifically for JuMP if that's ok. But this should otherwise work once that is sorted.

**Comment by odow** [comment]
@simonbowly looks like I'll need your input on this:

image

Did you test a WSL on your fork? Or some other type of license?

**Comment by odow** [comment]
@simonbowly and I discussed the license issue offline. It's now working.

However: @simonbowly when are the licenses validated? I'm seeing a lot of:
image
I assumed it would be whenever a new `Env` is created, but it seems that it might be on every call to optimize? Or periodically?

**Comment by odow** [comment]
It only took 8.5 years, but we now have CI! That coverage is a little shoddy though.

**Comment by simonbowly** [comment]
Great!  Thanks for all your work on this Oscar.

Re: the license checks, for WLS the license token needs to be refreshed periodically from the server.  The checks might occur periodically as well as on various API calls including .update() and .optimize() so I guess in tests it occurs pretty often.  It is probably not communicating with the server for every one of those messages though.

**Comment by szcf-weiya** [comment]
Thanks for the great package! I am using Gurobi.jl in my project, and also want to conduct a continuous integration in github actions. At first, it throws `No license` error,
image

then I tried to use a WSL license like what you did here, but now it throws
image

it seems that you also encountered the same issue (https://github.com/jump-dev/Gurobi.jl/pull/428#issuecomment-963486321); how did you finally manage it? Anything I have missed?

**Comment by odow** [comment]
> how did you finally manage it?

We use an undocumented/still-in-development feature, so for now there is probably no way for you to use Gurobi.jl in GitHub actions. If you have a commercial license, you should contact your support rep and they may be able to help you.

**Comment by szcf-weiya** [comment]
Got it, thanks for your explanation. Also just noticed README.md wrote
> However, we thank Gurobi for providing us with a license to test Gurobi.jl on GitHub.

**Pull request merged**
